/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef my_CONSTANTS_H
#define my_CONSTANTS_H

#include "my_types.h"

namespace Test {

class myConstants {
 public:
  myConstants();

};

extern const myConstants g_my_constants;

} // namespace

#endif
