/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "my_constants.h"

namespace Test {

const myConstants g_my_constants;

myConstants::myConstants() {
}

} // namespace

