/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RPCProxyServer_CONSTANTS_H
#define RPCProxyServer_CONSTANTS_H

#include "RPCProxyServer_types.h"

namespace Test {

class RPCProxyServerConstants {
 public:
  RPCProxyServerConstants();

};

extern const RPCProxyServerConstants g_RPCProxyServer_constants;

} // namespace

#endif
