/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RPCProxyServer_constants.h"

namespace Test {

const RPCProxyServerConstants g_RPCProxyServer_constants;

RPCProxyServerConstants::RPCProxyServerConstants() {
}

} // namespace

